#!/bin/bash

# Check if this is a symlink
if [ -L "$BASH_SOURCE" ]; then
    SCRIPT_PATH=`readlink $BASH_SOURCE`
    BASE_DIR=`dirname $SCRIPT_PATH`

else
    BASE_DIR=`dirname $BASH_SOURCE`
fi

SYS_DIR=$BASE_DIR/sys

proj() {

    SEARCH_TERM=$@

    if [ ! $SEARCH_TERM ]; then
        cd $PROJ_DIR
        ls
        return
    fi


    if [ -z "${PROJ_DIR+x}" ]; then
        echo "ERROR: The environment variable PROJ_DIR is not set"
        return
    fi

    SEARCH_PHRASE=$PROJ_DIR/*$SEARCH_TERM*

    num_files=$(ls -d $SEARCH_PHRASE 2> /dev/null|wc -l)
    if [ $num_files == "0" ]; then
        echo "ERROR: No files match '$SEARCH_PHRASE'"
        return
    fi

    if [ "$num_files" -gt 1 ]; then
        # Check for exact match
        if [ -d $PROJ_DIR/$SEARCH_TERM ]; then
            export PROJECT_DIR=$PROJ_DIR/$SEARCH_TERM
        else
            echo "ERROR: Matched too many files for '$SEARCH_PHRASE'"
            return
        fi
    else
        export PROJECT_DIR=$(ls -d $SEARCH_PHRASE)
    fi

    export ACTIVE_PROJECT=`basename $PROJECT_DIR`

    cd $PROJECT_DIR 
    install_scripts $SYS_DIR/*
}
